# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GongFuBrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaiwan_size', models.FloatField()),
                ('temp_C', models.IntegerField()),
                ('tea_qty', models.FloatField()),
                ('steep_num', models.IntegerField()),
                ('steep_times', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('picture', models.FileField(upload_to=b'')),
                ('origin', models.CharField(max_length=250)),
                ('tasting_notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WesternBrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_qty', models.FloatField()),
                ('temp_C', models.IntegerField()),
                ('tea_qty', models.FloatField()),
                ('min_brew_time', models.TimeField()),
                ('max_brew_time', models.TimeField()),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.Tea')),
            ],
        ),
        migrations.AddField(
            model_name='gongfubrew',
            name='tea_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea.Tea'),
        ),
    ]
